### ISSUE TITLE
Referring to different editions of the publication

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#95] opened 2019-04-05 17:34 UTC
NIST publications retain the same document identifier (docnumber + revision number) on minor revisions (incorporating Errata).

(Screenshot from https://csrc.nist.gov/publications/detail/sp/800-162/final, 2014 and 2019 are clearly considered two separate documents)

![image004](https://user-images.githubusercontent.com/11865/55645538-6f7f2980-580b-11e9-808c-d5f6166a92f4.png)

We need to find a way to refer to different editions of the publication.

**Comment by opoudjis** [comment] 2019-04-08 05:07
Which means that edition and revision are different concepts after all, and that the edition is identified by year/month. I don't want to identify edition and date of publication, that is much too grotesque.

**Comment by opoudjis** [comment] 2019-04-14 08:57
If NIST by default uses revision date to identify editions, then that's what we shall do as well. After all, that's what NistBib is going to be finding when it screen-scrapes the NIST site.

Hence use of revdate in https://github.com/metanorma/metanorma-nist/issues/88

**Comment by opoudjis** [comment] 2019-04-14 08:58
... Can I close this ticket?

**Comment by ronaldtse** [comment] 2019-04-15 06:42
It is confirmed that NIST drafts/publications can have an edition date of year, year-month and year-month-day. So I think these we could have separate "revision" (`revdate`: year + month + day) and "edition" (year, year+month or year+month+day) attributes.

**Comment by opoudjis** [comment] 2019-04-20 10:09
Then that's a distinction of published-date vs updated-date (or revdate).

**Comment by opoudjis** [comment] 2019-04-20 10:24
There is no universe in which "SP 800-162 (January 2014 (includes updates as of 02-25-2019))" (which appears in https://csrc.nist.gov/publications/detail/sp/800-162/archive/2014-01-16) is acceptable as a document identifier. You really think people are going to type all of that in to a document?

Never mind me refusing to implement it: this is now squarely @andrew2net's problem, becaust NistBib is going to struggle to differentiate between them.

This is pedantry, and pedantry that is getting in the way of electronic citation. The identifier can only be SP 800-162 (February 2019). The Jan 2014 version is Withdrawn!

Please talk some sense into them. And in any case, there is nothing for me to do in this ticket. The bibliographic item may have a distinct updated-date and published-date value, but this question is about "Referring to different editions of the publication", and that is the job of a document identifier. "SP 800-162 (January 2014 (includes updates as of 02-25-2019))"  is not an acceptable identifier.

**Comment by opoudjis** [comment] 2019-04-25 13:44
The problem we have here is that errata are identified by their update date only, and the update date shadows the publication date, as noted in #111.

But really, that's not going to work in citation:  "SP 800-162 (January 2014 (includes updates as of 02-25-2019))" can't be data entered. Retrieving the 2019 version of the bibliographic entry via "SP 800-162 (February 2019)" could identify that the 2019 date is an update date and not a publication date, and expand it back out to "SP 800-162 (January 2014 (includes updates as of 02-25-2019))".

**Comment by ronaldtse** [comment] 2019-04-26 16:33
@opoudjis and @andrew2net please note:

I've just received the final, confirmed method for short citations.

|Type | Short | Long |
|--|--|--|
|Undated reference | SP 800-162| |
|Final without `updated-date` | SP 800-162 (January 2014) | SP 800-162 (January 2014)
|Final where `updated-date` > `original-release-date` | SP 800-162 (February 25, 2019) | SP 800-162 (January 2014 (includes updates as of 02-25-2019))"

**Comment by opoudjis** [comment] 2019-04-29 10:00
... So they expect people to provide MMM DD, YYYY to specify errata releases. Which means realistically that identifier parsing will need to deal with MMM YYYY and MMM DD, YYYY dates.

So now we know that such references are going to be cited by published or update date, whichever shows up first.  The mechanics of citation does not care whatsoever within Metanorma, because it will cite what you provide it with as the document identifier, so that's the bibliography management system's problem; hence https://github.com/metanorma/nistbib/issues/12

The only thing Metanorma cares about is the three identifiers it will populate bibdata with. What I see is going on for those identifiers with errata releases is, obligatory appending update date if present for all three.

The problem is that NIST have dumped an even bigger issue here: if the publication is *not* an errata release, when are undated references used, and when are dated references used?

What I have gathered so far is there is no rule. The first published version is undated; revisions may be indicated by revision or by date; drafts may be indicated by date as well, but drafts are not properly citable, so I'm not going to agonise this.

The computer generated dates in NIST are not going to incorporate the publication date, because there is no clear rule, and the preference in the formulated rules in #88 is for revision numbers over dates. That will be overridden if necessary by specifying an explicit `docidentifier` document attribute, which can include the publication date instead of a revision number.

**Comment by opoudjis** [comment] 2019-04-29 10:08
Oh, this is even more confusing. I can't ignore the dates on drafts.

We have four dates in play, because of this perversity:

* published-date, for published documents, including published revisions
* updated-date, for errata releases, and minor updates in general to published documents
* circulated-date, for official release dates of drafts
* revdate, for informal updates to documents.

I am forced to do the following:

* Ignore published-date for appending a date to the publication: published documents are undated, and revisions are indicated by revision number instead of publication date
* Use updated-date where present, as an indication of an errata release
* Use circulated-date where present, as an indication of a draft date
* Use revdate only for drafts, and only where circulated-date is not present; a draft that has not been formally released should not be cited.

**Comment by opoudjis** [comment] 2019-04-29 11:40
The boilerplate date for when a document was last updated, accordingly, is now calculated on the same basis as above:

Most_RecentDate = if published: updated-date or published-date; else circulated-date or revdate.

**Comment by opoudjis** [comment] 2019-04-29 12:09
More dumb idiosyncracies.

The boilerplate use of the “Abbreviated form", per https://github.com/metanorma/metanorma-nist/issues/88 never has an update date. This needs to be stripped in metadata, and it needs to be stripped by regex (because we can't assume that a date will not be manually supplied in `:docidentifier:` as an override.)

**Comment by opoudjis** [comment] 2019-04-29 12:24
@andrew2net, I'm about to close this ticket because I've done all I can do with it for Metanorma, but it (I guess) gives you background for  https://github.com/metanorma/nistbib/issues/12.

**Closed** 2019-04-29 12:30 UTC
Labels: question
