### ISSUE TITLE
"*_images" directory is empty -- don't create them

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#55] opened 2019-03-16 16:25 UTC
1. As mentioned in another ticket, we should generate the Word file in TMPDIR, not local dir.
2. We don't want to create empty directories that the user has no idea about.

A user says:
> When I generate the HTML, it creates an images folder “XXX_images”, but it's empty.

Let's not cause confusion to them.

**Comment by opoudjis** [comment] 2019-03-18 00:18
1. if you've mentioned it in another ticket, then I'm going to ignore it here. I'm pretty sure I've already debugged it, and if you're finding it still happening, you will need to give me enough information to reproduce it.

**Comment by ronaldtse** [comment] 2019-03-18 10:10
@opoudjis I'm still seeing this in `mn-nist-documents`. (under `sources/`). Can you verify?

**Comment by opoudjis** [comment] 2019-03-19 11:55
I was referring to point 1 not 2, but that is covered now in https://github.com/metanorma/metanorma-standoc/issues/53

**Comment by opoudjis** [comment] 2019-03-19 12:06
Two distinct issues:

* For HTML output, get rid of the empty directory if it is never used. (It is in fact used if data-uri encoding is disabled.)
* For DOC output, get rid of the directory at the end of processing, as already happens for PDF processing: unlike the case for HTML, it will never be needed, since the images will have been incorporated into the Word document.

**Comment by opoudjis** [comment] 2019-03-19 12:37
For clarity, I have renamed the HTML directory {filename}_htmlimages, when it needs to be maintained because data-uri is disabled.

**Comment by opoudjis** [comment] 2019-03-19 12:37
Fixed in isodoc.

**Closed by opoudjis** 2019-03-19 12:37 UTC
Labels: bug
